package ss12_java_collection_framework.bai_tap.luyen_tap_array_list_va_linked_list.services;

import ss12_java_collection_framework.bai_tap.luyen_tap_array_list_va_linked_list.services.Service;

public interface TabletService extends Service {
}
